### PR TITLE
25 fix sfls segmentor2 d hxx narrowing warning

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
xref Slicer/Slicer#485

**Comment by jcfr** [comment]
Cc: @fedorov @naucoin

**Comment by fedorov** [comment]
cc: @gaoyi

**Comment by jcfr** [comment]
For info about traits, see https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch3.html#x34-290003.2

**Comment by fedorov** [comment]
Looks good to me, so I am going to merge so that we can observe the dashboard tomorrow.

@ebremer and @gaoyi please comment here if you have concerns.

**Comment by naucoin** [comment]
@fedorov @jcfr With this last set of changes, my checkout of SlicerPathology on win64/vs2013 is building with just a few warnings (5) about type conversions.

**Comment by fedorov** [comment]
Great news, thanks

**Pull request merged**
