### PR TITLE
BUG: Add error checking on parameters

### PR DESCRIPTION
**Pull request by naucoin**
Add tests that the parameters have been set, otherwise use the default values
from QuickTCGA/Logic/vtkQuickTCGA.cxx

Issue #42

### CODE REVIEW

**Comment by fedorov** [comment]
Looking at the file changes, indentation seems to be off

**Comment by naucoin** [comment]
I see it now, will fix and merge the two commits. For the record, the original file has tabs in it, my changes used spaces and looks the same in my emacs windown.

**Comment by naucoin** [comment]
@fedorov Done.

**Comment by fedorov** [comment]
Thanks!

**Pull request merged**
