### PR TITLE
Build system reorganization

### PR DESCRIPTION
**Pull request by jcfr**
Here are few changes to follow the changes also proposed into `SlicerOpenCV`. See https://github.com/SBU-BMI/SlicerOpenCV/pull/7

In a nutshell, it applies the following changes:
- Include `SlicerOpenCV` extension by calling `find_package(SlicerOpenCV REQUIRED)`. This will set `OpenCV_DIR` in the current scope.
- Update CMakeLists.txt to use `find_package(OpenCV 3.1 REQUIRED)`
- Update minimum required version of OpenCV to be the latest release 3.1. It provided a better integration with CMake.
- Move all modules as direct child of the root directory.
- Move `SlicerPathology` scripted module into its own folder. Also renamed the python module `Util` to `SlicerPathologyUtil`

Since the code base has been re-organized, consider doing a **clean build** of both `SlicerOpenCV` and `SlicerPathology`.

To build this extension, here is what I used on Ubuntu:

```
$ git clone git@github.com:jcfr/SlicerPathology.git
$ git checkout -b build-system-reorganization jcfr/build-system-reorganization
$ cmake -DSlicer_DIR=/home/jcfr/Projects/Slicer-Release/Slicer-build/ -DSlicerOpenCV_DIR=/home/jcfr/Projects/SlicerOpenCV-Release/inner-build/ ../SlicerPathology
$ make -j6
```

Todos:
- [x] Enable  packaging
- [x] Test and fix issues

Cc: @fedorov @naucoin

### CODE REVIEW

**Comment by jcfr** [comment]
After enabling packaging and [installing from file](http://wiki.slicer.org/slicerWiki/index.php/Documentation/4.5/SlicerApplication/ExtensionsManager#Installing_an_extension_without_network_connection) both SlicerOpenCV and SlicerPathology extensions, here is the error at startup:

```
Additional module paths ..: /home/jcfr/.config/NA-MIC/Extensions-24947/SlicerOpenCV/lib/Slicer-4.5/qt-loadable-modules, /home/jcfr/.config/NA-MIC/Extensions-24947/SlicerPathology/lib/Slicer-4.5/qt-loadable-modules, /home/jcfr/.config/NA-MIC/Extensions-24947/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules
  Error(s):
    Cannot load library /home/jcfr/.config/NA-MIC/Extensions-24947/SlicerPathology/lib/Slicer-4.5/qt-loadable-modules/libqSlicerQuickTCGAModule.so: (libQuickTCGALogic.so: cannot open shared object file: No such file or directory)
  Error(s):
    Cannot load library /home/jcfr/.config/NA-MIC/Extensions-24947/SlicerPathology/lib/Slicer-4.5/qt-loadable-modules/libqSlicerShortCutCoreModule.so: (libShortCutCoreLogic.so: cannot open shared object file: No such file or directory)
Number of registered modules: 151 
Number of instantiated modules: 151
```

**Comment by jcfr** [comment]
Packaged extension can now be installed.

I will now log issues for further improvement to avoid duplicated code.

**Comment by fedorov** [comment]
@jcfr thank you very much for working on this!

@ebremer please wait until @naucoin is done with the prerequisite pull request https://github.com/SBU-BMI/SlicerOpenCV/pull/7, and confirming this one is working fine for her, before doing anything else (unless you want to do those steps and testing in parallel, which of course you are welcome to do).

**Comment by naucoin** [comment]
@ebremer SlicerOpenCV has been updated with the new build system, I need to merge this pull request so that you can continue to build against it. Recommended: clean build in Slicer's ITKv4-build dir, and clean builds of both SlicerOpenCV and SlicerPathology.

**Comment by jcfr** [comment]
Then, assuming you have an up-to-date Slicer build tree ... 

```
Slicer_DIR=/home/jcfr/Projects/Slicer-Release/Slicer-build/


git clone git@github.com:SBU-BMI/SlicerOpenCV.git
mkdir SlicerOpenCV-Release && cd SlicerOpenCV-Release
cmake -DSlicer_DIR=$Slicer_DIR ../SlicerOpenCV
SlicerOpenCV_DIR=$(pwd)/inner-build
make -j6

git clone git@github.com:SBU-BMI/SlicerPathology.git 
mkdir SlicerPathology-Release && cd SlicerPathology-Release
cmake -DSlicer_DIR=$Slicer_DIR -DSlicerOpenCV_DIR=$SlicerOpenCV_DIR ../SlicerPathology
make -j6
```

Hth
Jc

**Pull request merged**
